from .acquisition import AcquireLiteratureSourceInput, acquire_literature_source
from .citations import FinalizeCitationsInput, finalize_citations
from .corpus import (
    IngestLiteratureFilesInput,
    QueryLiteratureCorpusInput,
    ingest_literature_files,
    query_literature_corpus,
)
from .models import (
    FindInPageResult,
    InPageMatch,
    LiteratureEvidenceRow,
    PaperRecord,
    PaperSearchHit,
    PublicPageSnapshot,
    PublicWebHit,
    PublicWebSearchResult,
    ResearchDepth,
)
from .openalex_client import OpenAlexClient
from .online_search_adapter import OnlineSearchAdapter
from .semanticscholar_client import SemanticScholarClient, SemanticScholarRateLimitError
from .tools import (
    FindInPageInput,
    GetOpenAlexRecordInput,
    GetSemanticScholarRecordInput,
    OpenPublicPageInput,
    RecommendSemanticScholarInput,
    SearchOpenAlexInput,
    SearchPublicWebInput,
    SearchSemanticScholarInput,
    WebSearchInput,
    find_in_page,
    get_openalex_record,
    get_semantic_scholar_record,
    open_public_page,
    recommend_semantic_scholar,
    search_openalex,
    search_public_web,
    search_semantic_scholar,
    web_search,
)

__all__ = [
    "ResearchDepth",
    "PaperRecord",
    "PaperSearchHit",
    "PublicWebHit",
    "PublicWebSearchResult",
    "PublicPageSnapshot",
    "InPageMatch",
    "FindInPageResult",
    "LiteratureEvidenceRow",
    "OpenAlexClient",
    "SemanticScholarClient",
    "SemanticScholarRateLimitError",
    "OnlineSearchAdapter",
    "AcquireLiteratureSourceInput",
    "acquire_literature_source",
    "IngestLiteratureFilesInput",
    "QueryLiteratureCorpusInput",
    "FinalizeCitationsInput",
    "ingest_literature_files",
    "query_literature_corpus",
    "finalize_citations",
    "WebSearchInput",
    "web_search",
    "SearchOpenAlexInput",
    "search_openalex",
    "SearchSemanticScholarInput",
    "search_semantic_scholar",
    "GetOpenAlexRecordInput",
    "get_openalex_record",
    "GetSemanticScholarRecordInput",
    "get_semantic_scholar_record",
    "RecommendSemanticScholarInput",
    "recommend_semantic_scholar",
    "SearchPublicWebInput",
    "search_public_web",
    "OpenPublicPageInput",
    "open_public_page",
    "FindInPageInput",
    "find_in_page",
]
