vasp_cpu:
  audiences: [materials_worker]
  machine: cpu_server_2
  number_node: 1
  cpu_per_node: 32
  queue_name: batch
  group_size: 1
  custom_flags:
    - "#SBATCH -t 10-00:00:00"
    - "#SBATCH --export=ALL"
  source_list: ["/public/home/chenhh/catmaster_code/catmaster_env_vasp.sh"]

vasp_cpu_neb:
  audiences: [materials_worker]
  machine: cpu_server_2
  number_node: 1
  cpu_per_node: 96
  queue_name: batch
  group_size: 1
  custom_flags:
    - "#SBATCH -t 10-00:00:00"
    - "#SBATCH --export=ALL"
  source_list: ["/public/home/chenhh/catmaster_code/catmaster_env_vasp.sh"]

mace_gpu:
  audiences: [materials_worker, ml_worker]
  machine: gpu_server
  number_node: 1
  cpu_per_node: 16
  gpu_per_node: 1
  queue_name: main
  group_size: 1
  custom_flags:
    - "#SBATCH --export=ALL"

xtb_cpu:
  audiences: [orca_xtb_worker]
  machine: cpu_server_2
  number_node: 1
  cpu_per_node: 32
  queue_name: batch
  group_size: 1
  custom_flags:
    - "#SBATCH -t 2-00:00:00"
    - "#SBATCH --export=ALL"
  source_list: ["/public/home/chenhh/catmaster_code/catmaster_env_xtb.sh"]

crest_cpu:
  audiences: [orca_xtb_worker]
  machine: cpu_server_2
  number_node: 1
  cpu_per_node: 32
  queue_name: batch
  group_size: 1
  custom_flags:
    - "#SBATCH -t 2-00:00:00"
    - "#SBATCH --export=ALL"
  source_list: ["/public/home/chenhh/catmaster_code/catmaster_env_xtb.sh"]

orca_cpu:
  audiences: [orca_xtb_worker]
  machine: cpu_server_2
  number_node: 1
  cpu_per_node: 32
  queue_name: batch
  group_size: 1
  custom_flags:
    - "#SBATCH -t 4-00:00:00"
    - "#SBATCH --export=ALL"
  source_list: ["/public/home/chenhh/catmaster_code/catmaster_env_orca.sh"]
