"""Canonical observation event names used by CatMaster runtime stores."""
from __future__ import annotations

LLM_CALL_START = "LLM_CALL_START"
LLM_CALL_END = "LLM_CALL_END"
LLM_ERROR = "LLM_ERROR"
LLM_RAW_REQUEST = "LLM_RAW_REQUEST"
LLM_RAW_RESPONSE = "LLM_RAW_RESPONSE"

TOOL_CALL_START = "TOOL_CALL_START"
TOOL_CALL_END = "TOOL_CALL_END"
TOOL_RAW_INPUT = "TOOL_RAW_INPUT"
TOOL_RAW_OUTPUT = "TOOL_RAW_OUTPUT"

RUN_START = "RUN_START"
RUN_END = "RUN_END"
RUN_PAUSED = "RUN_PAUSED"
RUN_STATE_CHANGE = "RUN_STATE_CHANGE"

TASKS_COMPILED = "TASKS_COMPILED"
TASK_START = "TASK_START"
TASK_SUMMARY = "TASK_SUMMARY"
TASK_END = "TASK_END"
TASK_DECISION = "TASK_DECISION"

CHAT_MESSAGE = "CHAT_MESSAGE"
MACHINE_TIME_RECORD = "MACHINE_TIME_RECORD"

CALL_TREE_EVENTS = (
    LLM_CALL_START,
    LLM_CALL_END,
    LLM_ERROR,
    TOOL_CALL_START,
    TOOL_CALL_END,
    LLM_RAW_REQUEST,
    LLM_RAW_RESPONSE,
    TOOL_RAW_INPUT,
    TOOL_RAW_OUTPUT,
)

LLM_END_EVENTS = (LLM_CALL_END, LLM_ERROR)
TOOL_END_EVENTS = (TOOL_CALL_END, TOOL_RAW_OUTPUT)
DECISION_EVENTS = (LLM_CALL_END, TASK_DECISION)
TASK_STATE_EVENTS = (
    TASKS_COMPILED,
    TASK_START,
    TASK_SUMMARY,
    TASK_END,
    RUN_START,
    RUN_END,
    RUN_PAUSED,
    RUN_STATE_CHANGE,
    TOOL_CALL_START,
    TOOL_RAW_INPUT,
)


__all__ = [
    "CALL_TREE_EVENTS",
    "CHAT_MESSAGE",
    "DECISION_EVENTS",
    "LLM_CALL_END",
    "LLM_CALL_START",
    "LLM_END_EVENTS",
    "LLM_ERROR",
    "LLM_RAW_REQUEST",
    "LLM_RAW_RESPONSE",
    "MACHINE_TIME_RECORD",
    "RUN_END",
    "RUN_PAUSED",
    "RUN_START",
    "RUN_STATE_CHANGE",
    "TASKS_COMPILED",
    "TASK_DECISION",
    "TASK_END",
    "TASK_START",
    "TASK_STATE_EVENTS",
    "TASK_SUMMARY",
    "TOOL_CALL_END",
    "TOOL_CALL_START",
    "TOOL_END_EVENTS",
    "TOOL_RAW_INPUT",
    "TOOL_RAW_OUTPUT",
]
