from __future__ import annotations

EVENT_POLL_INTERVAL = 15
MAX_EVENT_FEED = 500
MAX_EVENT_PAYLOAD_CHARS = 2000
MAX_TEXT_PREVIEW_CHARS = 20000
MAX_TRACE_LINES = 200

LIVE_SUMMARY_ENABLED_DEFAULT = True
LIVE_SUMMARY_MIN_INTERVAL_SEC = 30
LIVE_SUMMARY_TOOL_EVENT_BATCH = 8
LIVE_SUMMARY_MAX_EVENTS = 40
LIVE_SUMMARY_MAX_PARAMS_CHARS = 4096
LIVE_SUMMARY_MAX_JOURNAL_ITEMS = 5
LIVE_SUMMARY_TIMEOUT_SEC = 1.0
