from __future__ import annotations

# Re-export tool functions and input models
from catmaster.tools.geometry_inputs.molecule import MoleculeFromSmilesInput, create_molecule_from_smiles
from catmaster.tools.geometry_inputs.molecular_qchem import (
    EnumerateMolecularConformersInput,
    FilterConformerEnsembleInput,
    ExtractOptimizedMoleculesInput,
    enumerate_molecular_conformers,
    filter_conformer_ensemble,
    extract_optimized_molecules,
)
from catmaster.tools.geometry_inputs.orca_prepare import (
    OrcaPrepareInput,
    OrcaScanPrepareInput,
    OrcaOptTSPrepareInput,
    OrcaNebTSPrepareInput,
    OrcaIRCPrepareInput,
    orca_prepare,
    orca_scan_prepare,
    orca_optts_prepare,
    orca_nebts_prepare,
    orca_irc_prepare,
)
from catmaster.tools.geometry_inputs.cp2k_prepare import (
    Cp2kPrepareInput,
    cp2k_prepare,
)
from catmaster.tools.geometry_inputs.vasp_prepare import (
    VaspPrepareInput,
    vasp_prepare,
)
from catmaster.tools.geometry_inputs.vasp_band_prepare import (
    VaspBandPrepareInput,
    vasp_band_prepare,
)
from catmaster.tools.geometry_inputs.slab_tools import (
    SlabBuildInput,
    FixAtomsByLayersInput,
    FixAtomsByHeightInput,
    FixAtomsByIndicesInput,
    build_slab,
    fix_atoms_by_layers,
    fix_atoms_by_height,
    fix_atoms_by_indices,
)
from catmaster.tools.geometry_inputs.crystal_tool import (
    CreateVacancyInput,
    EnumerateUniqueSitesInput,
    GenerateKpathInput,
    GeneratePhononDisplacementsInput,
    GenerateStrainedStructuresInput,
    InsertInterstitialAtCoordsInput,
    SubstituteSpeciesInput,
    SupercellInput,
    create_vacancy,
    enumerate_unique_sites,
    generate_kpath,
    generate_phonon_displacements,
    generate_strained_structures,
    insert_interstitial_at_coords,
    substitute_species,
    supercell,
)
from catmaster.tools.geometry_inputs.adsorbate_tool import (
    EnumerateAdsorptionSitesInput,
    PlaceAdsorbateInput,
    GenerateBatchAdsorptionStructuresInput,
    enumerate_adsorption_sites,
    place_adsorbate,
    generate_batch_adsorption_structures,
)
from catmaster.tools.geometry_inputs.neb_tools import (
    EstimateNebImageCountInput,
    MakeNebGeometryInput,
    RemapNebEndpointAtomsInput,
    VaspNebPrepareInput,
    estimate_neb_image_count,
    make_neb_geometry,
    remap_neb_endpoint_atoms,
    vasp_neb_prepare,
)
from catmaster.tools.geometry_inputs.dimer_tools import (
    DimerModeFromMaceInput,
    MaceAnalyzeFrequenciesInput,
    DimerModeFromNebInput,
    VaspDimerPrepareInput,
    mace_analyze_frequencies,
    make_dimer_mode_from_mace,
    make_dimer_mode_from_neb,
    vasp_dimer_prepare,
)

__all__ = [
    "MoleculeFromSmilesInput",
    "create_molecule_from_smiles",
    "EnumerateMolecularConformersInput",
    "FilterConformerEnsembleInput",
    "ExtractOptimizedMoleculesInput",
    "enumerate_molecular_conformers",
    "filter_conformer_ensemble",
    "extract_optimized_molecules",
    "OrcaPrepareInput",
    "OrcaScanPrepareInput",
    "OrcaOptTSPrepareInput",
    "OrcaNebTSPrepareInput",
    "OrcaIRCPrepareInput",
    "orca_prepare",
    "orca_scan_prepare",
    "orca_optts_prepare",
    "orca_nebts_prepare",
    "orca_irc_prepare",
    "Cp2kPrepareInput",
    "cp2k_prepare",
    "VaspPrepareInput",
    "VaspBandPrepareInput",
    "SlabBuildInput",
    "FixAtomsByLayersInput",
    "FixAtomsByHeightInput",
    "FixAtomsByIndicesInput",
    "EnumerateAdsorptionSitesInput",
    "PlaceAdsorbateInput",
    "GenerateBatchAdsorptionStructuresInput",
    "EstimateNebImageCountInput",
    "RemapNebEndpointAtomsInput",
    "build_slab",
    "fix_atoms_by_layers",
    "fix_atoms_by_height",
    "fix_atoms_by_indices",
    "vasp_prepare",
    "vasp_band_prepare",
    "SupercellInput",
    "EnumerateUniqueSitesInput",
    "CreateVacancyInput",
    "SubstituteSpeciesInput",
    "InsertInterstitialAtCoordsInput",
    "GenerateStrainedStructuresInput",
    "GenerateKpathInput",
    "GeneratePhononDisplacementsInput",
    "supercell",
    "enumerate_unique_sites",
    "create_vacancy",
    "substitute_species",
    "insert_interstitial_at_coords",
    "generate_strained_structures",
    "generate_kpath",
    "generate_phonon_displacements",
    "enumerate_adsorption_sites",
    "place_adsorbate",
    "generate_batch_adsorption_structures",
    "estimate_neb_image_count",
    "remap_neb_endpoint_atoms",
    "MakeNebGeometryInput",
    "VaspNebPrepareInput",
    "VaspDimerPrepareInput",
    "DimerModeFromNebInput",
    "DimerModeFromMaceInput",
    "MaceAnalyzeFrequenciesInput",
    "make_neb_geometry",
    "vasp_neb_prepare",
    "vasp_dimer_prepare",
    "mace_analyze_frequencies",
    "make_dimer_mode_from_neb",
    "make_dimer_mode_from_mace",
]
