"""
Prepare MPRelax-style VASP input sets via StructWriter.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Literal
from ase.io import read as ase_read
from pydantic import BaseModel, Field, field_validator, model_validator
from pymatgen.core import Structure
from pymatgen.io.ase import AseAtomsAdaptor

from catmaster.runtime.tool_output_adapter import CatMasterToolExecutionError
from .vasp_inputs import StructWriter
from catmaster.tools.base import resolve_workspace_path, workspace_relpath


SUPPORTED_EXTS = {".vasp", ".cif"}
_ELEMENT_MAP_INCAR_KEYS = {"MAGMOM", "LDAUU", "LDAUJ"}


def _element_map_error_message(key: str) -> str:
    return (
        f"{key} must be an element-map in this tool due to pymatgen constraints, "
        'e.g. {"Fe": 2.2} or {"O": 1}.'
    )


def _coerce_element_map_value(key: str, raw_val: Any | None) -> Any | None:
    if raw_val is None:
        return None
    if not isinstance(raw_val, dict):
        raise ValueError(_element_map_error_message(key))
    normalized: Dict[str, Any] = {}
    for sym_raw, value in raw_val.items():
        symbol = str(sym_raw).strip()
        if not symbol:
            raise ValueError(_element_map_error_message(key))
        normalized[symbol] = value
    return normalized


def _normalize_user_incar_settings(
    value: Dict,
) -> Dict:
    normalized: Dict[str, Any] = {}
    for raw_key, raw_val in value.items():
        key = str(raw_key).strip().upper()
        if not key:
            raise ValueError("INCAR key must be a non-empty string.")
        if key in _ELEMENT_MAP_INCAR_KEYS:
            raw_val = _coerce_element_map_value(key, raw_val)
        normalized[key] = raw_val
    return normalized


class VaspRelaxPrepareInput(BaseModel):
    """
    Prepare MPRelaxSet-based VASP relax inputs with calc_type presets and k_product k-mesh.
    Also can be modified for other calculation types by overriding INCAR via the user_incar_settings.
    Support exts: .vasp, .cif

    Baseline DFT settings follow Materials Project MPRelaxSet (key defaults):
    - PBE54 POTCARS, ENCUT=520 eV, PREC=Accurate, ISPIN=2, IBRION=2, LREAL=AUTO, LASPH=True, LWAVE=False, LCHARG=False.
    - Additional overrides applied based on calc_type: ISMEAR=0, SIGMA=0.1 for bulk/slab; ISMEAR=0, SIGMA=0.01 for gas.
    - ISIF policy: bulk with relax_cell=False -> ISIF=2; bulk with relax_cell=True -> ISIF=3.
      slab and gas always use ISIF=2, where slab forces KPOINTS z=1 and gas forces KPOINTS 1x1x1 with ISYM=0.
    - Improved convergence settings: EDIFF=1e-6; NSW=500; EDIFFG=-0.02;
    - LORBIT is controlled by compute_dos (default False -> LORBIT=0, True -> LORBIT=11).
    - KPOINTS is generated by k*a=k_product, where a is the lattice constant in Angstrom. Set to 35 by default as the project house default for production slab work unless a tighter convergence study is required. Bulk references do not have to follow this slab-oriented default, and DOS-oriented jobs may intentionally raise the value (for example to 50) when warranted.
    - DFT-D3(BJ) and DFT+U are disabled by default. Enable them if the system is adsorption system(DFT-D3(BJ), IVDW=12) or transition metal oxide system(DFT+U).
    """

    input_path: str = Field(
        ...,
        description="Path to a structure file with lattice information (POSCAR/CIF) or a directory containing multiple structures. Support exts: .vasp, .cif",
    )
    output_root: str = Field(
        ...,
        description=(
            "Directory for generated VASP inputs. "
            "If input_path is a file, write directly into output_root/ without creating an extra <stem>/ layer. "
            "If that target directory already contains INCAR, the tool refuses to write and asks for a different output_root. "
            "If input_path is a directory, preserve relative subfolders as output_root/<relpath>/<stem>/..."
        ),
    )
    calc_type: Literal["gas", "bulk", "slab"] = Field(
        "bulk",
        description=(
            "Calculation type: 'gas'|'bulk'|'slab'. "
            "This provides preset INCAR overrides for different calculation types. gas is suitable for small molecules; slab is suitable for surface slab models; bulk is suitable for bulk relaxations."
        ),
    )
    relax_cell: bool = Field(
        False,
        description="Whether to relax cell shape/volume (ISIF=3). Only valid when calc_type='bulk'.",
    )
    k_product: int = Field(
        35,
        ge=1,
        description="Target k-mesh density via k_i~round(k_product/L_i), min 1, forced odd (Gamma-centered); gas always 1x1x1.",
    )
    use_d3: bool = Field(False, description="Enable DFT-D3(BJ) correction (IVDW=12). Enable it for adsorption calculations.")
    use_dft_plus_u: bool = Field(False, description="Enable DFT+U relevant settings according to materials project standard. Enable it for Transition Metal Oxide systems.")
    compute_dos: bool = Field(
        False,
        description="Enable DOS/projection output by setting LORBIT=11. Default false (LORBIT=0) to reduce disk usage.",
    )
    enable_dipole: bool = Field(
        False,
        description=(
            "Enable dipole correction helper. When true, default IDIPOL=3 and set DIPOL to the atomic center of mass of cell in fractional coordinates."
        ),
    )
    user_incar_settings: Dict = Field(
        default_factory=dict,
        description=(
            "User INCAR overrides as a json object as per pymatgen's user_incar_settings format, e.g. "
            '{"MAGMOM":{"O":1},"ALGO":"Fast"}. '
            "In this tool, due to pymatgen constraints, MAGMOM/LDAUU/LDAUJ must be provided as symbol:value maps. "
            "Use null only as a value inside the override object to remove a specific INCAR key, e.g. "
            "`{\"LREAL\": null}`. "
            "calc_type/task-required presets still take precedence on key conflict."
        ),
    )

    @field_validator("user_incar_settings")
    @classmethod
    def _validate_user_incar_settings(
        cls,
        value: Dict,
    ) -> Dict:
        return _normalize_user_incar_settings(value)

    @model_validator(mode="after")
    def _validate_relax_cell_conflict(self) -> "VaspRelaxPrepareInput":
        if self.relax_cell and self.calc_type in {"gas", "slab"}:
            raise ValueError("relax_cell=True is not allowed when calc_type is 'gas' or 'slab'.")
        return self


class VaspSPPrepareInput(BaseModel):
    """Prepare MPRelaxSet-based VASP single-point inputs for structures under a file or directory. Parameters are the same as VaspRelaxPrepareInput, but with single_point relaxation enabled (NSW=1, IBRION=-1). For a single input file, write directly into output_root/ and refuse reuse when that directory already contains INCAR."""

    input_path: str = Field(
        ...,
        description="Structure file or directory of structures. Supported: .vasp, .cif",
    )
    output_root: str = Field(
        ...,
        description=(
            "Directory for generated VASP inputs. "
            "If input_path is a file, write directly into output_root/ without creating an extra <stem>/ layer. "
            "If that target directory already contains INCAR, the tool refuses to write and asks for a different output_root. "
            "If input_path is a directory, keep one subfolder per structure."
        ),
    )
    calc_type: Literal["gas", "bulk", "slab"] = Field(
        "bulk",
        description="Calculation preset for k-mesh and INCAR defaults.",
    )
    k_product: int = Field(
        35,
        ge=1,
        description="k-mesh density via k_i~round(k_product/L_i), min 1.",
    )
    use_d3: bool = Field(False, description="Enable DFT-D3(BJ) correction (IVDW=12).")
    use_dft_plus_u: bool = Field(False, description="Enable DFT+U settings.")
    compute_dos: bool = Field(
        False,
        description="Enable DOS/projection output by setting LORBIT=11. Default false (LORBIT=0).",
    )
    enable_dipole: bool = Field(
        False,
        description=(
            "Enable dipole correction helper. When true, default IDIPOL=3 and set DIPOL to the atomic center of mass in fractional coordinates."
        ),
    )
    user_incar_settings: Dict = Field(
        default_factory=dict,
        description=(
            "User INCAR overrides as a json object as per pymatgen's user_incar_settings format, e.g. "
            '{"MAGMOM":{"O":1},"ALGO":"Fast"}. '
            "In this tool, due to pymatgen constraints, MAGMOM/LDAUU/LDAUJ must be provided as symbol:value maps. "
            "Use null only as a value inside the override object to remove a specific INCAR key, e.g. "
            "`{\"LORBIT\": null}`. "
            "calc_type/task-required presets still take precedence on key conflict."
        ),
    )

    @field_validator("user_incar_settings")
    @classmethod
    def _validate_user_incar_settings(
        cls,
        value: Dict,
    ) -> Dict:
        return _normalize_user_incar_settings(value)


def _load_structure(path: Path) -> Structure:
    if path.suffix.lower() == ".xyz":
        atoms = ase_read(path.as_posix())
        return AseAtomsAdaptor.get_structure(atoms)
    return Structure.from_file(path)


def _discover_structures(input_path: Path) -> List[Path]:
    if input_path.is_file():
        return [input_path]
    files = []
    for ext in SUPPORTED_EXTS:
        files.extend(sorted(input_path.rglob(f"*{ext}")))
    return files


def _prepare_structures(
    *,
    tool_name: str,
    input_path: Path,
    output_root: Path,
    calc_type: str,
    relax_cell: bool,
    k_product: int,
    user_incar_settings: Dict[str, Any],
    use_d3: bool,
    use_dft_plus_u: bool,
    compute_dos: bool,
    enable_dipole: bool,
    single_point: bool,
) -> tuple[str, dict[str, Any]]:

    output_root.mkdir(parents=True, exist_ok=True)
    writer = StructWriter()

    structures = _discover_structures(input_path)
    # Auto-detect batch vs single if not explicitly set:
    # - single file => single mode
    # - directory or multiple files => batch mode
    batch_mode = input_path.is_dir() or len(structures) > 1

    emitted: List[Dict[str, object]] = []
    errors: List[Dict[str, str]] = []
    for struct_path in structures:
        try:
            structure = _load_structure(struct_path)
            if input_path.is_dir():
                rel = struct_path.relative_to(input_path)
                rel_parent = rel.parent if rel.parent.as_posix() != "." else Path()
                out_dir = output_root / rel_parent / rel.stem
            else:
                out_dir = output_root
            incar_path = out_dir / "INCAR"
            if incar_path.exists():
                raise CatMasterToolExecutionError(
                    tool_name=tool_name,
                    public_message=(
                        f"{tool_name} refused to overwrite existing VASP inputs in {workspace_relpath(out_dir)} "
                        "because INCAR already exists there. Choose a different output_root."
                    ),
                    artifact={
                        "tool_name": tool_name,
                        "data": {
                            "input_path_rel": workspace_relpath(input_path),
                            "output_root_rel": workspace_relpath(output_root),
                            "conflict_dir_rel": workspace_relpath(out_dir),
                            "conflict_incar_rel": workspace_relpath(incar_path),
                            "calc_type": calc_type,
                            "relax_cell": relax_cell,
                            "single_point": single_point,
                            "compute_dos": compute_dos,
                            "enable_dipole": enable_dipole,
                            "k_product": k_product,
                            "structures_processed": len(emitted),
                            "errors": errors,
                        },
                    },
                    error_code="prepare_target_exists",
                )
            writer.write_vasp_inputs(
                structure=structure,
                output_dir=out_dir,
                calc_type=calc_type,
                relax_cell=relax_cell,
                k_product=k_product,
                use_d3=use_d3,
                use_dft_plus_u=use_dft_plus_u,
                user_incar_overrides=user_incar_settings,
                single_point=single_point,
                compute_dos=compute_dos,
                enable_dipole=enable_dipole,
            )
            emitted.append(
                {
                    "source_rel": workspace_relpath(struct_path),
                    "output_dir_rel": workspace_relpath(out_dir),
                }
            )
        except Exception as exc:
            errors.append({"source": workspace_relpath(struct_path), "error": str(exc)})
            if not batch_mode:
                if isinstance(exc, CatMasterToolExecutionError):
                    raise
                raise CatMasterToolExecutionError(
                    tool_name=tool_name,
                    public_message=(
                        f"{tool_name} failed for {workspace_relpath(struct_path)}: {exc}\n"
                        f"input_path_rel={workspace_relpath(input_path)}\n"
                        f"output_root_rel={workspace_relpath(output_root)}"
                    ),
                    artifact={
                        "tool_name": tool_name,
                        "data": {
                            "input_path_rel": workspace_relpath(input_path),
                            "output_root_rel": workspace_relpath(output_root),
                            "calc_type": calc_type,
                            "relax_cell": relax_cell,
                            "single_point": single_point,
                            "compute_dos": compute_dos,
                            "enable_dipole": enable_dipole,
                            "k_product": k_product,
                            "structures_processed": 0,
                            "errors": errors,
                        },
                    },
                    error_code="prepare_failed",
                )
        if not batch_mode:
            break

    first_prepared = emitted[0]["output_dir_rel"] if emitted else ""
    first_error = errors[0] if errors else {}
    data = {
        "input_path_rel": workspace_relpath(input_path),
        "output_root_rel": workspace_relpath(output_root),
        "calc_type": calc_type,
        "relax_cell": relax_cell,
        "single_point": single_point,
        "compute_dos": compute_dos,
        "enable_dipole": enable_dipole,
        "k_product": k_product,
        "structures_processed": len(emitted),
        "prepared_directories_rel": [str(e["output_dir_rel"]) for e in emitted],
        "errors_count": len(errors),
        "errors": errors,
    }
    lines = [
        f"{tool_name} completed.",
        f"structures_processed={len(emitted)} errors_count={len(errors)} calc_type={calc_type}",
        f"output_root_rel={data['output_root_rel']}",
    ]
    if first_prepared:
        lines.append(f"first_prepared_dir={first_prepared}")
    first_error_source = str(first_error.get("source") or "")
    if first_error_source:
        lines.append(f"first_error_source={first_error_source}")
    content = "\n".join(lines)
    return content, {
        "tool_name": tool_name,
        "data": data,
    }


def vasp_relax_prepare(payload: Dict[str, object]) -> tuple[str, dict[str, Any]]:
    params = VaspRelaxPrepareInput(**payload)
    return _prepare_structures(
        tool_name="vasp_relax_prepare",
        input_path=resolve_workspace_path(params.input_path),
        output_root=resolve_workspace_path(params.output_root),
        calc_type=params.calc_type,
        relax_cell=bool(params.relax_cell),
        k_product=int(params.k_product),
        user_incar_settings=dict(params.user_incar_settings),
        use_d3=bool(params.use_d3),
        use_dft_plus_u=bool(params.use_dft_plus_u),
        compute_dos=bool(params.compute_dos),
        enable_dipole=bool(params.enable_dipole),
        single_point=False,
    )


def vasp_sp_prepare(payload: Dict[str, object]) -> tuple[str, dict[str, Any]]:
    params = VaspSPPrepareInput(**payload)
    return _prepare_structures(
        tool_name="vasp_sp_prepare",
        input_path=resolve_workspace_path(params.input_path),
        output_root=resolve_workspace_path(params.output_root),
        calc_type=params.calc_type,
        relax_cell=False,
        k_product=int(params.k_product),
        user_incar_settings=dict(params.user_incar_settings),
        use_d3=bool(params.use_d3),
        use_dft_plus_u=bool(params.use_dft_plus_u),
        compute_dos=bool(params.compute_dos),
        enable_dipole=bool(params.enable_dipole),
        single_point=True,
    )


__all__ = [
    "VaspRelaxPrepareInput",
    "VaspSPPrepareInput",
    "vasp_relax_prepare",
    "vasp_sp_prepare",
]
