from __future__ import annotations

ROLE_SKILL_NAMES: dict[str, list[str]] = {
    "proposal": [
        "literature-grounding",
        "materials-discovery-and-bulk-selection",
        "slab-construction-and-surface-modeling",
        "surface-and-termination-screening",
        "adsorption-site-screening",
        "adsorption-screening",
        "structure-visual-inspection",
        "thermo-free-energy-and-reporting",
        "neb-prepare",
        "neb-calculation",
        "neb-analysis",
    ],
    "director": [
        "literature-grounding",
        "materials-discovery-and-bulk-selection",
        "slab-construction-and-surface-modeling",
        "surface-and-termination-screening",
        "adsorbate-and-intermediate-generation",
        "adsorption-site-screening",
        "adsorption-screening",
        "mlff-screening-and-relaxation",
        "structure-visual-inspection",
        "vasp-input-preparation",
        "vasp-batch-execution",
        "neb-prepare",
        "neb-calculation",
        "mlff-path-optimization",
        "mlff-vibrational-analysis",
        "mlff-transition-state-refinement",
        "neb-analysis",
        "thermo-free-energy-and-reporting",
    ],
    "fast_director": [
        "literature-grounding",
        "materials-discovery-and-bulk-selection",
        "slab-construction-and-surface-modeling",
        "surface-and-termination-screening",
        "adsorbate-and-intermediate-generation",
        "adsorption-site-screening",
        "adsorption-screening",
        "mlff-screening-and-relaxation",
        "structure-visual-inspection",
        "vasp-input-preparation",
        "vasp-batch-execution",
        "neb-prepare",
        "neb-calculation",
        "mlff-path-optimization",
        "mlff-vibrational-analysis",
        "mlff-transition-state-refinement",
        "neb-analysis",
        "thermo-free-energy-and-reporting",
    ],
    "task_runner": [
        "materials-discovery-and-bulk-selection",
        "slab-construction-and-surface-modeling",
        "surface-and-termination-screening",
        "adsorbate-and-intermediate-generation",
        "adsorption-site-screening",
        "adsorption-screening",
        "mlff-screening-and-relaxation",
        "structure-visual-inspection",
        "vasp-input-preparation",
        "vasp-batch-execution",
        "neb-prepare",
        "neb-calculation",
        "mlff-path-optimization",
        "mlff-vibrational-analysis",
        "mlff-transition-state-refinement",
        "neb-analysis",
        "thermo-free-energy-and-reporting",
    ],
    "research_lead": [
        "literature-grounding",
        "materials-discovery-and-bulk-selection",
        "slab-construction-and-surface-modeling",
        "surface-and-termination-screening",
        "adsorption-site-screening",
        "adsorption-screening",
        "structure-visual-inspection",
        "neb-prepare",
        "neb-calculation",
        "neb-analysis",
        "thermo-free-energy-and-reporting",
    ],
    "research_state_updater": [
        "literature-grounding",
        "materials-discovery-and-bulk-selection",
        "slab-construction-and-surface-modeling",
        "surface-and-termination-screening",
        "adsorption-site-screening",
        "adsorption-screening",
        "structure-visual-inspection",
        "neb-prepare",
        "neb-calculation",
        "neb-analysis",
        "thermo-free-energy-and-reporting",
    ],
    "write_director": [],
    "section_writer": [],
    "plot_worker": [],
    "write_reviewer": [],
}


def role_visible_skill_names(role: str) -> list[str]:
    return list(ROLE_SKILL_NAMES.get(str(role or "").strip(), []))


__all__ = ["ROLE_SKILL_NAMES", "role_visible_skill_names"]
