#!/usr/bin/env python3
"""
DPDispatcher demo: VASP relaxation of O2 on cpu_hpc.
- Uses prepared inputs from tests/assets/O2_in_the_box
- Dry-run by default; add --run to actually submit
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path
from pprint import pprint

from catmaster.tools.execution import vasp_execute

ASSETS = Path(__file__).resolve().parents[1] / "tests" / "assets" / "CO_VASP_inputs"


def stage_inputs(workspace: Path) -> Path:
    workspace.mkdir(parents=True, exist_ok=True)
    dest = workspace / "CO_VASP_inputs"
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(ASSETS, dest)
    # runner script will be generated by vasp_execute helper
    return dest


def main() -> None:
    parser = argparse.ArgumentParser(description="Run O2 VASP via DPDispatcher")
    parser.add_argument("--workspace", default="workspace/demo_vasp_CO", help="Local workspace root")
    parser.add_argument("--run", action="store_true", help="Actually submit; default prints payload")
    args = parser.parse_args()

    input_dir = stage_inputs(Path(args.workspace))

    payload = {
        "input_dir": str(input_dir),
        "check_interval": 60,
    }

    print("Planned payload (cpu_hpc VASP):")
    pprint(payload)

    if not args.run:
        print("Dry-run only. Use --run to submit via DPDispatcher.")
        return

    result = vasp_execute(payload)
    print("\nSubmission result:")
    pprint(result)
    print("\nDownloaded results directory:", result.get("data", {}).get("download_path"))


if __name__ == "__main__":
    main()
